apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rafin1998/rafin-blog-site:1.1-frontend
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rafin1998/rafin-blog-site:0.3
          ports:
            - containerPort: 6000
          env:
            - name: SECRET_KEY
              value: "63eaQmNBpg"
            - name: API_KEY
              value: "@Beginning@After@the@ENd@"
            - name: APP_SETTINGS
              value: project.server.config.ProductionConfig
            - name: POSTGRES_SERVER_NAME
              value: 103.209.42.222
            - name: POSTGRES_USER
              value: rafin_vm
            - name: POSTGRES_PASSWORD
              value: raf1n%40%40vm
            - name: FLASK_APP
              value: manage.py

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 30000
  selector:
    app: backend