"""Initial migration based on current models

Revision ID: b98020cc10fb
Revises: 
Create Date: 2024-08-20 15:02:57.043398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b98020cc10fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=False)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
