"""Testimonial company field added

Revision ID: d00b6fc5a6cf
Revises: dbca4e0dc1d7
Create Date: 2024-08-18 11:28:38.646466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00b6fc5a6cf'
down_revision = 'dbca4e0dc1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=False))
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('company')

    # ### end Alembic commands ###
